-- Create Archives Table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.archives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    type TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    company_name TEXT,
    status TEXT DEFAULT 'saved',
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Ensure RLS is enabled
ALTER TABLE public.archives ENABLE ROW LEVEL SECURITY;

-- Reset policies to avoid conflicts
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.archives;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.archives;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.archives;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.archives;
DROP POLICY IF EXISTS "Enable delete access for all users" ON public.archives;
DROP POLICY IF EXISTS "Enable all access for anon and authenticated" ON public.archives;

-- Create a permissive policy for ALL users (authenticated and anonymous/public)
-- This allows the "Secret Master Access" mode (which is anonymous) to work alongside authenticated users.
CREATE POLICY "Enable all access for anon and authenticated" ON public.archives
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);

-- Grant necessary permissions to the anon and authenticated roles
GRANT ALL ON TABLE public.archives TO anon;
GRANT ALL ON TABLE public.archives TO authenticated;
GRANT ALL ON TABLE public.archives TO service_role;
