-- COPY THIS ENTIRE SCRIPT AND RUN IT IN SUPABASE SQL EDITOR

-- 1. Create table with correct columns and defaults
CREATE TABLE IF NOT EXISTS public.archives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    type TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    company_name TEXT,
    status TEXT DEFAULT 'saved',
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 2. Ensure columns exist (for updates to existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='archives' AND column_name='company_name') THEN
        ALTER TABLE public.archives ADD COLUMN company_name TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='archives' AND column_name='user_id') THEN
        ALTER TABLE public.archives ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE public.archives ENABLE ROW LEVEL SECURITY;

-- 4. Reset Policies (Drop old ones to be safe)
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.archives;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.archives;
DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.archives;

-- 5. Create Permissive Policy for Authenticated Users
CREATE POLICY "Enable all access for authenticated users" ON public.archives
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 6. Grant Permissions
GRANT ALL ON TABLE public.archives TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE archives_id_seq TO authenticated;
